run:
  go: '1.17'
  timeout: 2m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - vendor
    - proto
    - gen

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gosec:
    checks:
      - all
      - '-G404'
      - '-G102'
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-tags:
      - experimental
  gocyclo:
    min-complexity: 20
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  testpackage:
    skip-regexp: (export|internal|)_test\.go
  nolintlint:
    require-specific: true
    require-explanation: true
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - asciicheck
    - gochecknoglobals
    - gocognit
    - nestif
    - prealloc
    - testpackage
    - exportloopref
    - gas
    - errorlint
    - durationcheck
    - bodyclose
    - contextcheck
    - bidichk
    # - lll # disabled for now as it will error in many things that are improductive to fix atm
    # - gofumpt # ideally we would like to use it, but has been flaky recently
    # - gomnd # ideally we would like to use it, but might give lots of alerts due to assigned variables (need more investigation on how to use it)

issues:
  exclude:
    - "^G102.*"
    - "^G404.*"
  exclude-rules:
    - path: _test\.go
      linters:
        - lll #expected output for TestCompile are v long
        - funlen
        - dupl # excluding dupl check on tests - many tests follow the same format as they're auto generated by the IDE