services:

  reviews:
   build:
     context: ./
     dockerfile: ./services/reviews/Dockerfile
     args:
       PROJECT: ./services/reviews
   environment:
     - APP_NAME=reviews
     - MONGODB_URI=mongodb://mongo:27017/
     - TELEMETRY_ENABLED=true
     - TELEMETRY_JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
   ports:
     - "8001:50051"
     - "2222:2222"
   restart: on-failure
   volumes:
     - ./:/usr/src/app
     - go-modules:/go/pkg/mod
   networks:
     - monorepo_net
   depends_on:
     - mongo
     - jaeger

  products:
    build:
      context: ./
      dockerfile: ./services/products/Dockerfile
      args:
        PROJECT: ./services/products
    environment:
      - APP_NAME=products
      - MONGODB_URI=mongodb://mongo:27017/
      - TELEMETRY_ENABLED=true
      - TELEMETRY_JAEGER_COLLECTOR_ENDPOINT=http://jaeger:14268/api/traces
    ports:
      - "8002:50051"
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - go-modules:/go/pkg/mod
    networks:
      - monorepo_net
    depends_on:
      - mongo
      - jaeger

  envoy:
    image: envoyproxy/envoy:v1.21.1
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./services/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    restart: on-failure
    networks:
      - monorepo_net

  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    networks:
      - monorepo_net
    command: --quiet --logpath /dev/null

  jaeger:
    image: jaegertracing/all-in-one:latest
    command: --log-level=warn
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - monorepo_net

networks:
  monorepo_net:
    driver: bridge

volumes:
  go-modules: