name: protos

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.5.0

      - run: buf format --diff --exit-code .

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          against: 'https://github.com/braderz/monorepo.git#branch=main,ref=HEAD~1,subdir=proto'