name: Docker build and push

on:
  workflow_call:
    inputs:
      service:
        required: true
        description: "Name of the service you wish to build. It must be in the services directory and it must have a Dockerfile specified under its folder."
        type: string


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/${{ inputs.service}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # login to github package registry for docker containers
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The builds require buildx to work, also so we can use github cache for docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Simple tagging policy for now
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push the docker image to github packages. Using github actions cache for layers.
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: services/${{ inputs.service }}/Dockerfile
          build-args: |
            PROJECT=./services/${{ inputs.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max