name: golangci-lint

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read # Required for `only-new-issues` option.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: 'go.mod'

      - uses: golangci/golangci-lint-action@v3
        with:
          args: --out-${NO_FUTURE}format colored-line-number --verbose
          only-new-issues: true