name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: 'go.mod'
          
      - name: start test dependencies
        run: docker compose up -d mongo

      - name: go test
        run: go test ./... -race